[routers]
r1 ansible_host=192.168.101.50 ansible_network_os=cisco.ios.ios

[switches]
sw1 ansible_host=10.0.0.2 ansible_network_os=cisco.ios.ios

[network:children]
routers
switches

[network:vars]
ansible_connection=ansible.netcommon.network_cli
ansible_user={{ lookup('env', 'TF_VAR_sshuser') }}
ansible_password={{ lookup('env', 'TF_VAR_sshpw') }}
ansible_become=yes
ansible_become_method=enable
ansible_become_password={{ lookup('env', 'TF_VAR_sshpw') }}
